### PR TITLE
Added plan and subscriptions

### LINKED ISSUE #168: support for plan and subscriptions
I see mercadopago sdk for php already have support for plan and subscriptions:
https://github.com/mercadopago/dx-php/blob/ec571266495cb96bb5b7a4ae8073dcca822a3e5d/samples/suscriptions/subscribe-to-plan.php

I couldn't find any example of how to implement this with dx-nodejs and I understand this feature is not implemented at the moment  (pls correct me if I'm wrong).

From my pov of view plans and subscriptions should be supported.

### PR DESCRIPTION
**Pull request by LuKks**
Closes #168.

This is work in progress because you don't have tests for /v1/customers API and the subscription requires a customer id.
The PHP library also doesn't have a example to create a customer either tests.
Also there is no API reference (or I didn't found it) for /v1/plans and /v1/subscription so I can't guess every status for the model.

I think I can do tests for plans at least but I want a confirmation that it works fine.

You can install it to test with:
`npm i lukks/dx-nodejs`

At this moment we need to know at least if the models are right, I know that the enum status are incorrect, how I can know every possible status? as I said before, there is no docs for it.

### CODE REVIEW

**Comment by manuargue** [comment]
This is how I managed to make it work from postman (using sandbox):

POST create a customer (returns the customer details)
https://api.mercadopago.com/v1/customers?access_token=TEST-123
```
{ "email":"customer@test.com" }
```

POST add a card to the customer (needs at least one card to subscribe to a plan)
https://api.mercadopago.com/v1/customers/171269569-l1buINeP84/cards?access_token=TEST-123
`{ "token":"9b2d63e00d66a8c721607214cedaec" }`

the only way I found to generate the card token was using [this form](https://gist.github.com/kainlite/a32aab7f7a68094d1d38848495320873). I filled the card details using one of test cards published in mercadopago. After submitting the form you can console.log the token created by the mercadopago js sdk.

POST create plan
https://api.mercadopago.com/v1/plans?access_token=TEST-123
```
{
	"description":"my plan",
	"auto_recurring": {
		"frequency":1,
		"frequency_type":"months",
		"transaction_amount":15.0,
		"currency_id":"ARS"
	}
}
```

POST subscribe customer to plan
https://api.mercadopago.com/v1/subscriptions?access_token=TEST-123
```
{
	"plan_id": "a5a8b6e1721148c58c72bd11e60",
	"payer":{
		"id":  171269569-l1buINeP84
	}
}
```

to test if it's working, setup mercadopago webhooks to receive subscriptions & plans notifications.

**Comment by dsouza95** [comment]
@LuKks, I have created an user and tested creating and cancelling subscriptions using the SDK + web tokenize checkout. So far, no problems! Thanks for the pull request :)

**Comment by manuargue** [comment]
Has somebody tested it in production environment? I was notified from mercadopago support that plan/subscriptions API are being migrated to a new architecture, therefore not available for production. Although in sandbox environment it seems to be working fine...

**Comment by LuKks** [comment]
I think you should use `preapproval` and `authorized_payment`.
I did examples in #154 but it gets complicated if you want a complete solution.
As I said, maybe we need a library that wraps everything and leaves a simple API.
If plans and subscriptions are deprecated then you should not aim to use them, I did this PR because I saw some people wanting it.

Anyway, four different APIs (`preapproval`, `authorized_payment`, `plans`, `subscriptions`) related to make a subscription? Five if you count the payment API.

- `preapproval` is very fine, at least is what worked for me, but why it also brings `authorized_payment`? Can't we just have a single API for it?

- When you pay a `preapproval` with your current money of your MercadoPago account (I mean no card transaction), in that case the `expire_date` field will be empty, so you need to guess the expiration based on your plans, and also giving extra days because you can do your user's plan expire in a wrong date.

- In `preapproval` you have `payer_id` and `payer_email` but in `payment` you have `payer.id` and `payer.email`, it seems inconsitent so it would be great having just a `payer` object.

- There are webhooks and IPN, why we can't just have a single way to do notifications?

Let me put it on this way, was more easy to do [genetic neural networks](https://github.com/LuKks/neural-go) in Go (like 5 days) than integrating a complete solution for `preapproval` (like 2 weeks).
And we are not even talking about access token, test users, sandbox, etc.

Something not related but is a opportunity for improvement is that we need to wait two days before the preapproval payment is actually made, that is very annoying for an application where a user subscribes to something and needs to wait >=2 days to receive the service.

**That are a few thoughts about the current API available that I hope can be used to improve the next API.**

**Comment by dsouza95** [comment]
> Has somebody tested it in production environment? I was notified from mercadopago support that plan/subscriptions API are being migrated to a new architecture, therefore not available for production. Although in sandbox environment it seems to be working fine...

Tried to use this on production, but no cigar. I get a 401 error with the following message: "Unauthorized request to Plans". Seems I will have to use the preapproval, but it doesn't seem to be very straightforward...

**Comment by LuKks** [comment]
@dsouza95 Try the basic implementation (consider it pseudo-code):
https://gist.github.com/LuKks/07dd061832bc56bc40516fe107308b86
I added `mp.ipn.authorized_payment` inside of the `payment` notification because at the moment I did that code I wasn't receiving the authorized_payment notifications correctly.
*This explanation and code is already in the #154, unfortunately it's in Spanish but you can translate or ask if something is not understandable.

Probably you already have the latest version but really ensure it because sometime ago I fixed a small error related with the cancelled status, you can't have preapproval properly working without that fix.
Fixed in >=1.0.24

**Comment by dsouza95** [comment]
@LuKks, sounds good, I'll give that a try. Thanks!

**Comment by julianmojico** [comment]
> @LuKks, I have created an user and tested creating and cancelling subscriptions using the SDK + web tokenize checkout. So far, no problems! Thanks for the pull request :)

Did you use sandbox credentials? 
As others mentioned, POST request is not working with prod credentials :(

> Has somebody tested it in production environment? I was notified from mercadopago support that plan/subscriptions API are being migrated to a new architecture, therefore not available for production. Although in sandbox environment it seems to be working fine...

**Pull request closed without merging**
