### PR TITLE
Add types to use with typescript

### PR DESCRIPTION
**Pull request by TheRafaelFarias**
When install this lib in typescript project, don't have the types.

VsCode say to install "@types/mercadopago" but don't exists, will be cool add the types

### CODE REVIEW

**Comment by cold-briu** [comment]
I think it is more than cool to add the types. 
TS is eating the whole JS ecosystem and mercadopago should support it. 
We want to use your services, mercadopago, please make our life easier just as TS does.

**Comment by TheRafaelFarias** [comment]
> I think it is more than cool to add the types.
> TS is eating the whole JS ecosystem and mercadopago should support it.
> We want to use your services, mercadopago, please make our life easier just as TS does.

Exactly, this project is appearing to be abandoned, Add the types will help not just us like they too

**Comment by danieldspx** [comment]
@TheRafaelFarias  @cold-briu @vicenteign @dsg38 @vractos Could you guys [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49745/files) since it will add types to this package. Also There is a lot of inconsistency between the SDK and the API (defined in the [website](https://www.mercadopago.com.br/developers/pt/reference/)). I even tryed to open a PR to this repo (dx-nodejs) to fix some stuff but they do not seem to care. The SDK is very outdated but for basic usage it is ok.

**Comment by danieldspx** [comment]
Guys, this PR (Shouldn't it be a Issue?) can be closed sice we now have the types at https://www.npmjs.com/package/@types/mercadopago

**Comment by GbalsaC** [comment]
Interface for `CreatePreferencePayload` is incomplete, it's missing the following properties: `purpose` and `binary_mode`.

Even though this parameters are specified [in the docs](https://www.mercadopago.com.mx/developers/es/guides/online-payments/checkout-pro/configurations/) 

Interface needs to be extended:

``` typescript
export interface CreatePreferencePayload {
  /** Informações sobre o item. */
  items?: PreferenceItem[];
  /** Informações sobre o comprador. */
  payer?: PreferencePayer;
  /** Métodos de pagamento a ser excluídos do fluxo de pagamento. */
  payment_methods?: PreferencePaymentMethods;
  /** Informações de envio. */
  shipments?: PreferenceShipment;
  /** Url de retorno ao site do vendedor. */
  back_urls?: PreferenceBackUrl;
  /** URL para a qual você gostaria de receber notificações de pagamentos. */
  notification_url?: string;
  /** Como aparecerá o pagamento no extrato do cartão (ex: o MERCADOPAGO). */
  statement_descriptor?: string;
  /** Informações adicionais. */
  additional_info?: string;
  /**
   * No caso de estar especificado o comprador será redirecionado para o seu site imediatamente após a compra.
   * approved = The redirection takes place only for approved payments.
   * all = The redirection takes place only for approved payments, forward compatibility only if we change the default behavior
   */
  auto_return?: 'approved' | 'all';
  /** Referência que pode sincronizar com seu sistema de pagamentos. */
  external_reference?: string;
  /** Preferência que determina se uma preferência expira. */
  expires?: boolean;
  /** Data (ISO_8601) de expiração de meios de pagamento em dinheiro. */
  date_of_expiration?: string;
  /** Data (ISO_8601) a partir da qual a preferência estará ativa. */
  expiration_date_from?: string;
  /** Data (ISO_8601) em que a preferência expira. */
  expiration_date_to?: string;
  /** Origem do pagamento. Valor por defeito: NENHUM */
  marketplace?: string;
  /** Comissão de Mercado cobrada pelo proprietário do aplicativo. Valor por default: 0 em moeda local */
  marketplace_fee?: number;
  /** Configuração de preço diferencial para esta preferência. */
  differential_pricing?: {
    /** Identificador de preço diferenciado. */
    id: number;
  };
  /** Tracks que serão executados durante a interação do usuário no fluxo de Pagamento. */
  tracks?: PreferenceTrack[];
}
```

**Comment by danieldspx** [comment]
> Interface for `CreatePreferencePayload` is incomplete, it's missing the following properties: `purpose` and `binary_mode`.
> 
> Even though this parameters are specified [in the docs](https://www.mercadopago.com.mx/developers/es/guides/online-payments/checkout-pro/configurations/)
> 
> Interface needs to be extended:
> 
> ```ts
> export interface CreatePreferencePayload {
>   /** Informações sobre o item. */
>   items?: PreferenceItem[];
>   /** Informações sobre o comprador. */
>   payer?: PreferencePayer;
>   /** Métodos de pagamento a ser excluídos do fluxo de pagamento. */
>   payment_methods?: PreferencePaymentMethods;
>   /** Informações de envio. */
>   shipments?: PreferenceShipment;
>   /** Url de retorno ao site do vendedor. */
>   back_urls?: PreferenceBackUrl;
>   /** URL para a qual você gostaria de receber notificações de pagamentos. */
>   notification_url?: string;
>   /** Como aparecerá o pagamento no extrato do cartão (ex: o MERCADOPAGO). */
>   statement_descriptor?: string;
>   /** Informações adicionais. */
>   additional_info?: string;
>   /**
>    * No caso de estar especificado o comprador será redirecionado para o seu site imediatamente após a compra.
>    * approved = The redirection takes place only for approved payments.
>    * all = The redirection takes place only for approved payments, forward compatibility only if we change the default behavior
>    */
>   auto_return?: 'approved' | 'all';
>   /** Referência que pode sincronizar com seu sistema de pagamentos. */
>   external_reference?: string;
>   /** Preferência que determina se uma preferência expira. */
>   expires?: boolean;
>   /** Data (ISO_8601) de expiração de meios de pagamento em dinheiro. */
>   date_of_expiration?: string;
>   /** Data (ISO_8601) a partir da qual a preferência estará ativa. */
>   expiration_date_from?: string;
>   /** Data (ISO_8601) em que a preferência expira. */
>   expiration_date_to?: string;
>   /** Origem do pagamento. Valor por defeito: NENHUM */
>   marketplace?: string;
>   /** Comissão de Mercado cobrada pelo proprietário do aplicativo. Valor por default: 0 em moeda local */
>   marketplace_fee?: number;
>   /** Configuração de preço diferencial para esta preferência. */
>   differential_pricing?: {
>     /** Identificador de preço diferenciado. */
>     id: number;
>   };
>   /** Tracks que serão executados durante a interação do usuário no fluxo de Pagamento. */
>   tracks?: PreferenceTrack[];
> }
> ```

Ok, I have fixed it here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49858
@GbalsaC next time you can open an issue at DefinitelyTyped regarding to `mercadopago` type definition , here is not the right place for this kind of discussion. Thanks in advance.

**Comment by TheRafaelFarias** [comment]
> Guys, this PR (Shouldn't it be a Issue?)

Yes should be, but for some reason, we can't open issues
Thanks to @danieldspx to created the first types. 

In some time we gonna need to fork and continue the project, or even create a new one from scratch for the JS community have a good SDK

**Comment by danieldspx** [comment]
> > Guys, this PR (Shouldn't it be a Issue?)
> 
> Yes should be, but for some reason, we can't open issues
> Thanks to @danieldspx to created the first types.
> 
> In some time we gonna need to fork and continue the project, or even create a new one from scratch for the JS community have a good SDK

I suggest creating a new sdk from scratch (already with typescript) and make the mercadopago's api doc better since the official api documentation has a lot of missing properties and others silly erros. While we don't have a sdk built from scratch, you can help contributing to the type definition at DefinitelyTyped.

**Pull request closed without merging**
